stages:
  - deploy

deploy:
  stage: deploy
  environment:
    name: production
  only:
    - master
  script:
    - npm i
    - npm run build
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod